- name: "Setup Remote Geth"
  hosts: "{{ play_hosts }}"
  remote_user: "{{default_user}}"

- import_playbook: include/setup_user.yml
- import_playbook: include/setup_docker.yml
- import_playbook: include/install_porter.yml
- import_playbook: include/run_porter.yml
