# TODO: Turn these into classes?
HASH_DIGEST_LENGTH = 32

NOT_SIGNED = 445
NO_DECRYPTION_PERFORMED = 455

# These lengths are centric to secp256k1
KFRAG_LENGTH = 194
CFRAG_LENGTH = 131
CAPSULE_LENGTH = 98
