name: 🧹 Ruff

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
