name: Run Towncrier and Commit

on:
  push:
    branches:
      - main

jobs:
  towncrier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install Towncrier and Nucypher
      run: |
        python3 -m pip install towncrier
        pip install -e .

    - name: Run Towncrier
      run: |
        towncrier build --yes

    - name: Get Version
      id: get_version
      run: |
        VERSION=$(python setup.py --version)
        echo "::set-output name=version::$VERSION"

    - name: Setup Git and Commit
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Publish v${{ steps.get_version.outputs.version }} release notes."
        git push origin HEAD:main
